namespace: demo

replicaCount: 1

image:
  repository: frontend-bff
  tag: "dev"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

ingress:
  enabled: true
  className: traefik
  host: demo.lebedev.ai
  annotations: {}
  path: /
  pathType: Prefix

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

probes:
  path: /api/health
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 2
  failureThreshold: 3

env:
  PORT: "3000"
  APP_NAME: "Frontend BFF"
  NEXT_PUBLIC_APP_NAME: "Frontend BFF"
  NEXT_PUBLIC_STAGE: "default"
  BACKEND_BASE_URL: ""
  BACKEND_LOCAL_URL: ""
  BACKEND_CLUSTER_URL: "http://backend-api.demo.svc.cluster.local/api"

podAnnotations: {}

nameOverride: ""
fullnameOverride: ""
