namespace: demo

image:
  tag: "demo"

env:
  APP_NAME: "Demo Frontend BFF"
  NEXT_PUBLIC_APP_NAME: "Demo Frontend BFF"
  NEXT_PUBLIC_STAGE: "demo"
  BACKEND_BASE_URL: ""
  BACKEND_LOCAL_URL: ""
  BACKEND_CLUSTER_URL: "http://backend-api.demo.svc.cluster.local/api"
