import Link from 'next/link';

export const metadata = {
  title: 'Terms and Conditions | Messy Notes Demo',
};

export default function TermsPage() {
  return (
    <main className="shell policy-shell">
      <header className="topbar">
        <Link className="brand" href="/">
          <span className="brand-mark">D</span>
          <span>
            <strong>Messy Notes Demo</strong>
            <small>Limited-access demo</small>
          </span>
        </Link>

        <nav className="topnav" aria-label="Terms navigation">
          <Link href="/">Invite shell</Link>
          <Link href="/messy-notes">Workspace</Link>
          <Link href="/privacy">Privacy</Link>
        </nav>

        <p className="topbar-status">Terms</p>
      </header>

      <article className="policy-document">
        <p className="eyebrow">Terms and Conditions</p>
        <h1>Terms and Conditions</h1>
        <p className="section-detail">Effective date: May 1, 2026</p>

        <p>
          These Terms and Conditions govern your access to and use of this
          limited-access demo operated by Peter Lebedev.
        </p>

        <h2>Use of the Demo</h2>
        <p>
          This site is provided for demonstration, evaluation, and testing
          purposes only. You may use the demo only in a lawful manner and only
          for its intended purpose.
        </p>

        <h2>No Guarantee</h2>
        <p>
          The demo is provided on an &ldquo;as is&rdquo; and &ldquo;as
          available&rdquo; basis, without warranties of any kind. We do not
          guarantee that the demo will be uninterrupted, error-free, secure, or
          suitable for any particular purpose.
        </p>

        <h2>No Professional Advice</h2>
        <p>
          Outputs generated by the demo are for informational and demonstration
          purposes only and should not be treated as legal, financial, medical,
          compliance, or other professional advice.
        </p>

        <h2>User Content</h2>
        <p>
          You are responsible for any text, notes, files, phone numbers, email
          addresses, or other information you submit to the demo. You represent
          that you have the right to submit that information and that doing so
          does not violate any law or third-party rights.
        </p>

        <h2>Acceptable Use</h2>
        <p>You agree not to:</p>
        <ul>
          <li>misuse, disrupt, or interfere with the demo</li>
          <li>attempt unauthorized access to systems or data</li>
          <li>submit unlawful, harmful, infringing, or abusive content</li>
          <li>use the demo to send spam or unwanted communications</li>
          <li>
            reverse engineer, scrape, or abuse the service beyond reasonable
            evaluation use
          </li>
        </ul>

        <h2>Invitations and Access</h2>
        <p>
          Access to the demo may require an invitation code. Invitation codes
          may be limited, revoked, or disabled at any time.
        </p>

        <h2>SMS and Email Communications</h2>
        <p>
          If you choose to provide your email address or phone number, you agree
          that we may send communications related to your use of the demo,
          including invitation emails and optional SMS notifications.
        </p>
        <p>
          Message frequency varies. Message and data rates may apply. You can
          opt out of SMS at any time by replying STOP.
        </p>

        <h2>Intellectual Property</h2>
        <p>
          The demo, including its design, software, workflows, and content
          created by the operator, is owned by Peter Lebedev or its licensors
          and is protected by applicable intellectual property laws. These Terms
          do not give you any ownership rights in the demo.
        </p>

        <h2>Termination</h2>
        <p>
          We may suspend, restrict, or terminate access to the demo at any time,
          with or without notice, including if we believe the demo is being
          misused.
        </p>

        <h2>Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by law, Peter Lebedev shall not be
          liable for any indirect, incidental, special, consequential, or
          punitive damages, or for any loss of data, profits, goodwill, or
          business opportunity arising out of or related to your use of the
          demo.
        </p>

        <h2>Changes</h2>
        <p>
          We may update these Terms and Conditions from time to time by posting
          the updated version on this site.
        </p>

        <h2>Contact</h2>
        <p>If you have questions about these Terms and Conditions, contact:</p>
        <p>
          <a href="mailto:pete.lebedev@gmail.com">pete.lebedev@gmail.com</a>
        </p>
      </article>
    </main>
  );
}
